version: '3.9'

services:
  postgres_database:
    image: postgres:14.8-alpine
    container_name: DbLabContainer
    restart: always
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - db_data_14:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
volumes:
  db_data_14: