version: '3.9'

services:
  postgres_database:
    image: postgres:14.8-alpine
    container_name: DbLabContainer
    restart: always
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - db_data_14:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

  mongo_database:
    image: mongo:latest
    container_name: MongoDbLabContainer
    restart: always
    ports:
      - '27017:27017' # Maps the default MongoDB port to the same port on the host
    volumes:
      - mongo_data_14:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    command: ["mongod", "--replSet", "rs0"]

volumes:
  db_data_14:
  mongo_data_14:
